Repository alex-bezpalko/homepage, pull requests merged in 2019-05, with the labels that each got.

#3 First release to production
  index.html
Labels: release

#10 add base.css stylesheet link
  index.html
Labels: enhancement

#11 add primary content
  assets/images/lionel-messi.svg
  index.html
Labels: enhancement

#12 add secondary content
  index.html
Labels: enhancement

#13 add content
  assets/images/lionel-messi.svg
  index.html
Labels: enhancement

#14 Release to production
  assets/images/lionel-messi.svg
  index.html
Labels: release

#16 Release to production
  .gitignore
  .travis.yml
  sw.js
  workbox-config.js
Labels: release

#17 My take on reordering page content for readability
  index.html
Labels: enhancement

#18 Bring more order to page
  index.html
Labels: enhancement, release

#20 small fix
  index.html
  sw.js
Labels: enhancement, release
